---
- hosts: localhost
  vars_files:
    - ./common-vars.yml

  tasks:
    - name: Install and setup environment for Debian
      import_tasks: debian-tasks.yml
      when: ansible_distribution == 'Archlinux'

  tasks:
    - name: Install and setup environment for Debian
      import_tasks: debian-tasks.yml
      when: ansible_distribution == 'Debian'
  
  handlers:
    - name: Handlers for Debian
      import_tasks: debian-handlers.yml
      when: ansible_distribution == 'Debian'

  handlers:
    - name: Handlers for Manjaro
      import_tasks: manjaro-handlers.yml
      when: ansible_distribution == 'Archlinux'

