---
- hosts: "{{ target | default('localhost', true) }}"
  vars_files:
    - ./common-vars.yml

  tasks:
    - name: Install and setup environment for Manjaro
      include_role:
        name: archlinux
      when: ansible_distribution == 'Archlinux'
      tags: always

    - name: Install and setup environment for Debian
      include_role:
        name: debian
      when: ansible_distribution == 'Debian'
      tags: always
